spring.application.name=retrieval-augmented-generation-demo
spring.docker.compose.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5432/smart_alec
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=1536
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=EUCLIDEAN_DISTANCE

spring.ai.openai.api-key=${OPEN_API_KEY}

